USE [master]
GO
/****** Object:  Database [SimonsTestDB]    Script Date: 1/10/2018 12:55:23 PM ******/
CREATE DATABASE [ClinicalHealthCare]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClinicalHealthCare', FILENAME = N'D:\SaddamHusaain\2018\DataBase\Mdf\ClinicalHealthCare.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClinicalHealthCare_log', FILENAME = N'D:\SaddamHusaain\2018\DataBase\Log\ClinicalHealthCare_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ClinicalHealthCare] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClinicalHealthCare].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ClinicalHealthCare] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ClinicalHealthCare] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClinicalHealthCare] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClinicalHealthCare] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ClinicalHealthCare] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClinicalHealthCare] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ClinicalHealthCare] SET  MULTI_USER 
GO
ALTER DATABASE [ClinicalHealthCare] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClinicalHealthCare] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ClinicalHealthCare] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ClinicalHealthCare] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [ClinicalHealthCare]
GO
/****** Object:  Table [dbo].[Medications]    Script Date: 1/10/2018 12:55:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Medications](
	[MedicationId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Dosage] [varchar](255) NOT NULL,
	[Frequency] [varchar](255) NOT NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[Prescriber] [varchar](255) NOT NULL,
	[RXNumber] [varchar](250) NOT NULL,
	[Notes] [varchar](1000) NULL,
	[Active] [bit] NOT NULL,
	[CreatedDate] [datetime] NULL,
 CONSTRAINT [PK_Medications] PRIMARY KEY CLUSTERED 
(
	[MedicationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Medications] ADD  CONSTRAINT [DF_Medications_Active]  DEFAULT ((0)) FOR [Active]
GO
USE [master]
GO
ALTER DATABASE [ClinicalHealthCare] SET  READ_WRITE 
GO
